### ISSUE TITLE
Implement support for Spritemaps

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#3162]
Since we now have a zoom feature, it would be nice to have higher-resolution graphics. This will mean an increase in filesize though, so we should have support for spritemaps.

There have been 2 approaches to implement utils/make_spritemap.py this so far:

1. A grid that joins the images together (trunk)
2. A compact spritemap that analyzes the image content and saves a lot of space (lp:~widelands-dev/widelands/spritemaps_testing)

I have attached an image comparing the 2 approaches.

I have pretty much implemented the C++ part for the second approach, but the python script still needs work if we want to use that. I would be in favor of option 2 if we can fix the script.

Either script would need adjusting so they will write to Lua format rather than the old conf format.

# Implementation steps

- [x] Implement mipmaps https://en.wikipedia.org/wiki/Mipmap
- [ ] Implement simple spritesheets (option 1). Bob animations have big changes from frame to frame, so it won't be possible to make them more compact. #3489
- [ ] Convert graphics
- [ ] Write a test https://github.com/gunchleoc/widelands/tree/test-animations
- [ ] Implement compact spritesmaps (Option 2). These will be useful for immovables. https://github.com/gunchleoc/widelands/tree/spritemaps-experiment

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2016-11-01T18:48:55Z
 * owner: gunchleoc
 * assignee: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1638356

**Comment by bunnybot** [comment]
(by gunchleoc)

**Comment by bunnybot** [comment]
(by sirver)
I am also in favor of 2, but instead of using the python script, I would rewrite it in c++. When this script was started, our build system did not easily allow multiple binaries to be built. And the code could benefit from having access to the graphics system and the lua dictionary parsing that is already implemented in c++.

**Comment by bunnybot** [comment]
(by gunchleoc)
+1 to #2

**Comment by bunnybot** [comment]
(by gunchleoc)
My current plan is the following:

1. Implement mipmaps https://en.wikipedia.org/wiki/Mipmap

2. Implement simple spritesheets (option 1). Bob animations have big changes from frame to frame, so it won't be possible to make them more compact.

3. Now we can start converting graphics

4. Implement compact spritesmaps (Option 2). These will be useful for immovables.

**Comment by bunnybot** [comment]
(by gunchleoc)
See also https://bugs.launchpad.net/widelands/+bug/1121982

**Comment by bunnybot** [comment]
(by franku)
Savegame needs much time to load

**Comment by gunchleoc** [comment]
Branches:
* https://github.com/gunchleoc/widelands/tree/spritemaps-experiment
* https://github.com/gunchleoc/widelands/tree/spritesheet-generation

**Comment by Noordfrees** [comment]
Compacted spritesheets will probably become a must-have for 1.1 as the data directory is very large already and will surely become even larger over time

**Comment by Noordfrees** [comment]
If we use an indexed palette for our PNGs we can reduce image size a lot. E.g. the amazon dressmakery working spritesheet at scale 4 goes down from 1.4 MB to 366 kB when using indexing (~**74%** smaller). Its PC mask goes from 14.3 kB to 11.8 kB (17%).

The downside of indexing is that we lose partial transparency: All semi-transparent areas (shadows on the ground) are replaced by either full transparency or opaque colour. Also it adds some sharp edges, though you only see those if you look closely. Compare:

![idle_4](https://user-images.githubusercontent.com/48293446/148955764-451a54b9-4783-47e7-a63e-86612c540e78.png) ![idle_4_indexed](https://user-images.githubusercontent.com/48293446/148955770-18e05376-fc88-42d0-b906-720e6fd7ffcf.png)
*&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Current master &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Indexed version*

Is this a major problem, or should we index lots of PNGs to reduce datadir size? Opinions please :)
@hessenfarmer @frankystone @tothxa 


---

Note: Even better compression can be achieved with this simple IM command
```sh
$ convert name.png PNG8:name.png
```

**Comment by hessenfarmer** [comment]
I think the hard edges and especially fully black shadow is a major problem. But to be finally sure I'd like to see the new model in game, to decide about it.   
has the console command the same effects? or how is compression achieved? would be nice to see this in game as well.

**Comment by tothxa** [comment]
The transparency issue is not a limitation of the PNG format itself, see https://en.wikipedia.org/wiki/Portable_Network_Graphics#Transparency_of_image, only of many popular PNG creation programs unfortunately.

**Comment by Noordfrees** [comment]
Current master:
![shot0000](https://user-images.githubusercontent.com/48293446/149296576-fe6ce457-e4c6-441c-9a15-98dfe40a2686.png)
Same image with *all* PNGs in the game converted to indexed:
![shot0001](https://user-images.githubusercontent.com/48293446/149296579-09cbeadf-a804-4c83-a96b-4c883f577aa8.png)

---

I also found another tool called pngquant that can handle semi-transparency in 8-bit PNGs:

![working_4](https://user-images.githubusercontent.com/48293446/149297165-804e16e4-527d-4917-b64d-913057c68dad.png)

```
pngquant 256 < working_4.png > /tmp/image && mv /tmp/image working_4.png
```

This image is less strongly compressed though:
Original - 1.4 MB
Convert - 244.5 kB
PNGQuant - 369.0 kB

Looks pretty good though, doesn't it?

**Comment by hessenfarmer** [comment]
the black shadows of PNG8 converted Images as seen in the in game screenshot are a NoGo from my side.
however the PNgquant file looks promising. I compared it to the master and couldn't see much difference even in high zoom in my webbrowser. Only noticeable at high zoom factor is a a potential higher contrast in the PNGquant image, which is probably even desirable.  
So to keep it short PNGquant is the way to go from my side.

Edit. can we use the tool in a scripted way as we have done in the past to optimize the PNG quality

**Comment by tothxa** [comment]
The PNGQuant docs say you can get further reduction in file size if you run a compression optimizer like pngcrush/optipng/oxipng afterwards.

**Comment by tothxa** [comment]
optipng after pngquant is only ~1.5% further decrease. oxipng seems to be newer and better, but it's still not packaged for debian, and is written in rust, so I couldn't try it so easily.
However the player colour files are effectively 1 bit already, so you don't need pngquant for them, optipng alone reduces your example from 14.3kB to 3.4kB.

**Comment by Noordfrees** [comment]
I've run pngquant across all PNGs and achieved a reduction of the whole datadir from 814 to 414 MB. I'm pushing the branch now (which takes several times longer than the actual conversion :wink:) and will open a PR later. 

We also have a script `utils/optimize_pngs.py` which applies various such tools. I did not manage to get pngquant working with it (its in-place option seems somewhat erratic, I need to use a temp file) so I added a pngquant wrapper as a standalone script. 

I skipped using optipng because as you say there's very little difference, and pngquant alone can also reduce the PC mask to 3.4 kB.

**Comment by tothxa** [comment]
OTOH pngquant --nofs --posterize 4 makes it 314kB (15% decrease compared to default pngquant), and I can't see any difference on my laptop screen, except for the shadow which got a little darker.

edit:
This is not universal though. If there are smooth colour transitions (like in https://www.widelands.org/forum/topic/5285/?page=3#post-37585), they get striped.
