### ISSUE TITLE
Decide what to do with Launchpad labels

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3473]
After we have organized our current milestone, decide what to do with the Launchpad Priority & status labels and then clean them up

# Status

- [x] New: Moved to "To Do" column in https://github.com/widelands/widelands/projects/2. Delete when their triage is complete
- [x] Incomplete: Moved to "In Progress" column in https://github.com/widelands/widelands/projects/2. Delete when their triage is complete
- [x] Confirmed: Can be deleted
- [x] Triaged: Can be deleted
- [x] In Progress: Ensure that somebody is assigned to the issue if the person is still active
- [x] Fix Commited: == Issue closed. Remove when #3462 is complete
- [x] Fix Released: == Milestone closed. Remove when #3462  is complete

# Priority

- [x] Undecided
- [x] Critical: Make sure it's on top of the milestone when #3462 is complete
- [x] High
- [x] Medium
- [x] Low
- [x] Wishlist: Replace with "enhancement" #3472

**Comment by gunchleoc** [comment]
I have roughly sorted the issues in the milestone according to priorities, so the priority labels can be deleted

**Comment by gunchleoc** [comment]
Since newly created issues end up on top of the issue triage, we can remove the "New" label right now and be done with it.
