### ISSUE TITLE
Enhance gamechatpanel

### ISSUE THREAD

**Issue by jmoerschbach** [widelands/widelands#3943]
As of now, gamechatpanel does not support copy'n'paste as one is used to from literally every text edit component in modern systems

**Implementation steps**
- [ ] Enable text selection (via shift+arrow keys)
- [ ] Enable text copy (via strg+c) 
- [ ] Enable text insertion (via strg+v)
