### ISSUE TITLE
Improve delayed hanlding of GUI Events

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5019]
Please fill out the relevant sections below and delete the rest.

**Is your feature request related to a problem? Please describe.**

As of the new Multithreading in current master: When you click on some GUI Element,
the Event will processed by the GUT Thread, then by the game Logic Thread and finally become visble
via the rendering Thread. As we send "set to absoulute value" Events, Mutiple clicks will
results in Noops.

**Describe the solution you'd like**

Change the events to increase/decrease events so the gui can send mutiple events
with the expected effect.

**Describe alternatives you've considered**

* Disable the GUI until the event was processsed. (will make things slower)
* Compare with a relase build

**Additional context**

Will try to add some video, later.

**Implementation steps**
- [ ] Add new "increment" events 
- [ ] Deprecate old events (if possible) 
- [ ] Make GUI use new Events
