### ISSUE TITLE
Get Rid Of Boost

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5115]
This issue is to keep track of my progress in completely getting rid of our boost dependencies.

### Low hanging fruit
- [x] String functions (#5101)
- [x] Unify format interface (#5081)

### Next on the hit list
- [x] Format (#5118)
- [x] Signals2 (#5133)
- [x] Unit tests (#5122)

### Might be slightly harder
- [x] asio networking (#5164)
- [X] SHA1 computation and random UUID generation (#5124)

### When we're already at it
- [X] Replace `std::rand` with `base/random.h struct RNG` (#5124)

**Comment by SirVer** [comment]
@Noordfrees Can you outline why you want to get rid of boost as dependency?

**Comment by Noordfrees** [comment]
There are some good posts about the drawbacks of Boost [here](https://gamedev.stackexchange.com/questions/8980/why-dont-c-game-developers-use-the-boost-library) and [here](https://www.reddit.com/r/cpp/comments/gfowpq/why_you_dont_use_boost/), but mostly this is about Boost being by a large margin the dependency that gives us the greatest amount of recurring compatibility trouble:

- https://www.widelands.org/wiki/BuildingWidelandsUnderWindowsNew/#cmake-cant-find-the-boost-package
- #4998
- #4556
- #4057
- #3905
- #3569
- #3372
- #3164
- #5100
- the list goes on…

I can't think of any other dependency that forced us via a regular update to rewrite over 400 lines of [code](https://github.com/widelands/widelands/pull/3907) during a feature freeze, and no other single dep requires anywhere near as many fixes and updates from us.

The points in the threads linked above also apply; the majority of the stuff that Boost offers and which we actually use is either part of the C++11 standard or has questionable complexity or can be written ourself easily.

The amount of effort we (have to) put into maintaining this dependency is out of all proportion to the advantages it offers for us, so it should go.

**Comment by SirVer** [comment]
I am too far removed from the daily development to truly judge if the trouble is worth the effort, I can only judge the effort - which seems pretty large to me. Your argumentation makes sense to me though, it just seems like a very big task.

**Comment by tothxa** [comment]
If this effort succeeds, it will be a benefit for flatpak packaging as well. Boost is the only external library that's not included in the freedesktop.org runtime and SDK, neither in the semi-official submodules (https://github.com/flathub/shared-modules/pull/14). Boost build and installation in the flatpak build environment takes about as long as the actual compilation of Widelands afterwards, and its build and installation log is much longer than Widelands's.

**Comment by tothxa** [comment]
> ### Might be slightly harder
> 
>     * [ ]  asio networking _(perhaps do it similar to net add-ons code)_

Sorry if you were already aware of it, but `asio` is available as a separate library as well:
* https://think-async.com/Asio/AsioAndBoostAsio.html
* https://github.com/chriskohlhoff/asio

It is packaged in Debian and Ubuntu as libasio-dev. Though it `recommends` some boost-dev libraries.

**Comment by Noordfrees** [comment]
Thanks! I had not known that, that's great news :)
