### ISSUE TITLE
Missing lore and production info in Empire/Atlantean building help

### ISSUE THREAD

**Issue by Wuzzy2** [widelands/widelands#5268]
**Describe the bug**
If you play as the Empire or Atlanteans and open the building help for any of the building, there is a section called "Lore" and "Production" that is currently empty.
For the lore it shows "Text needed" and for the "Production" section is shows "Calculation needed".

Other tribes seems t

**To Reproduce**
1. Play as Empire or Atlanteans
2. Click on any building to open the building help
3. Scroll through the window to see if my claims above are true

**Expected behavior**
The sections "Lore" and "Production" have actual contents instead of dummy texts.

**Version:**
 - Widelands Version: 1.0

#### Lore
 - [ ] Amazons lore: @alasiax had some very nice and imaginative work on this (#5037), but unfortunately she's been inactive since then
 - [x] Atlantean lore (#5271)
 - [x] Empire lore (#5285)
 - [ ] Frisian lore for rest of buildings

#### Production times
 - [x] Sites needing experience (#5768)
 - [x] Fix sleep times (#5778)
 - [x] Sites producing multiple wares (#5861)
 - [x] Small sites comparable between tribes (#6068)
 - [x] Medium sites comparable between tribes
 - [x] Big sites comparable between tribes
 - [x] Farm-like buildings
 - [x] Rest of amazons buildings
 - [x] Rest of atlanteans buildings
 - [x] Rest of barbarians buildings
 - [x] Rest of empire buildings
 - [x] Rest of frisians buildings

**Comment by klaus-halfmann** [comment]
Well this is not really a Bug but some missing texts, to be added . @Noordfrees  please tell us where we can add such texts, I would go ahead and invente some Lore and such.

Lore is "just" a bit of imagination describing the building in a funny way.

Production is something different, this should be done mathematically correct. One could derive some estimations by watching regular gameplay, which would be ok for the most players.

**Comment by Floy288** [comment]
Duplicate of #

**Comment by Noordfrees** [comment]
> Well this is not really a Bug but some missing texts, to be added . @Noordfrees please tell us where we can add such texts, I would go ahead and invente some Lore and such.

Lore texts are defined in the building's entry in `data/tribes/initialization/<tribename>/units.lua` by adding helptexts with the keys `lore` and `lore_author`, like this:

https://github.com/widelands/widelands/blob/eda47cde863b64577473b181950f5900bc4dee92/data/tribes/initialization/barbarians/units.lua#L1082-L1094

In the same way, the performance text is added as a helptext with the key `performance`:

https://github.com/widelands/widelands/blob/eda47cde863b64577473b181950f5900bc4dee92/data/tribes/initialization/barbarians/units.lua#L1156-L1157

**Comment by Wuzzy2** [comment]
Suggestion: When lore text is missing, hide the lore section in the help so this awkward dummy text is not shown.

**Comment by frankystone** [comment]
> Suggestion: When lore text is missing, hide the lore section in the help so this awkward dummy text is not shown.

I don't think it's awkward. Maybe just rephrase to something like: "Text needed. If you have an idea for a text please make a suggestion in the forums at https://www.widelands.org."

**Comment by klaus-halfmann** [comment]
OK, here is a branch where I will collect some lore for ATL, feel free to add your ideas.
https://github.com/widelands/widelands/tree/atl_lore

**Comment by hessenfarmer** [comment]
Maybe this might be discussed in a similar way then https://www.widelands.org/forum/topic/4193/

**Comment by Wuzzy2** [comment]
I looked at this again and I discovered the missing lore actually affects all tribes. List of buildings with missing lore:

* Almost all Atlantean buildings
* Almost all Empire buildings
* Almost all Amazonian buildings
* Barbarians: Ferry Yard, alternative Headquarters
* Frisians: Coal Mine, Deep Coal Mine, Deep Gold Mine, Deep Iron Mine, Deep Rock Mine, Ferry Yard, Fortress, Gold Mine, Headquarters, High Wooden Tower, Hunter's House, Iron Mine, Outpost, Port, Rock Mine, Sentinel, Tower, Warehouse, Wooden Tower

And production info seems to be missing across all over the place (sometimes it's there, sometimes not).

> I don't think it's awkward. Maybe just rephrase to something like: "Text needed. If you have an idea for a text please make a suggestion in the forums at https://www.widelands.org."

It's awkward because this "Text needed" reads like an unprofessional "TODO" to me, a developer comment that I would not expect from a version 1.0. As lore is not really important, I think it's a good fallback option to hide the word "Lore" and the "Text needed" altogether when this info is missing, it looks much less unprofessional to me.

Besides, your suggested text does not really work for add-on tribes (what if the author has gone missing in action, or never was on the forums? etc. etc.) anyway. Therefore I think just hiding the word "Lore" when lore is missing is best, especially for add-on tribes. My small suggestion also holds true when all official tribes have completed lore (which is already being worked on, which is nice :-) ).

**Comment by klaus-halfmann** [comment]
@Wuzzy2 give us some time or start inventing some lore for the EMP like I do with ATL. Its a creative process that should not be done in a hurry. I hope you played all the EMP Scenarios and got an Idea how empire "feels". If you think about terms like "pax romana", get inspired by "Quo Vadis" or whatever Imperial powers. This is open source and you are invited to contribute. You may register yourself at transifex so you can help with the translation of the lore, which will be fun and tricky. Version 1.0 was about feature completeness, not about having all polished and shiny. Yes this is a TODO, and thanks for reminding us.

**Comment by Wuzzy2** [comment]
No rush.

**Comment by tothxa** [comment]
I've realised that Empire will be easy: just collect some classical Latin quotes, and use those along with a translation. I already have  a few in mind, so I'll create a draft PR later today, but I don't want to spend too much time on it until the graphics re-export is ready for testing.

**Comment by klaus-halfmann** [comment]
@tothxa Great ! give me a link and we can start to do some kind of P2P review

**Comment by klaus-halfmann** [comment]
@Wuzzy2 please take a look here https://github.com/widelands/widelands/actions/runs/1894680815#artifacts
It still need some polishing, but I think I got some reasaonable / funny lores.

**Comment by gpalino** [comment]
For the missing performance texts, I estimate to split work into these PRs:
Sites comparable between tribes - small buildings (#6068)
Sites comparable between tribes - medium buildings
Sites comparable between tribes - big buildings
Farm-like buildings
Rest of amazons buildings
Rest of atlanteans buildings
Rest of barbarians buildings
Rest of empire buildings
Rest of frisians buildings

**Comment by bunnybot** [comment]
[<img align='left' src='https://codeberg.org/avatars/593dc43e2444c25db9481960e5b693ab' alt='tothxa' height='48' />](https://codeberg.org/tothxa)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/4104#issuecomment-7858217)*
*On Wed Oct 22 20:49:11 CEST 2025, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:*

---

20 out of 59 Frisian buildings also miss lore texts:
frisians_headquarters
frisians_warehouse
frisians_port
frisians_hunters_house
frisians_dikers_house
frisians_rockmine
frisians_rockmine_deep
frisians_coalmine
frisians_coalmine_deep
frisians_ironmine
frisians_ironmine_deep
frisians_goldmine
frisians_goldmine_deep
frisians_wooden_tower
frisians_wooden_tower_high
frisians_sentinel
frisians_outpost
frisians_tower
frisians_fortress
frisians_ferry_yard
