### ISSUE TITLE
Ideas for replay enhancements

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5649]
Re https://github.com/widelands/widelands/issues/5644#issuecomment-1302252481 and [this forum post](https://www.widelands.org/forum/post/39559/)

Maybe it would be possible to facilitate stepping back the time in replays if the autosaves during the game were also stored in the replay file. As save files can be quite big, this is probably only desirable if an efficient way can be found to compress the consecutive autosave deltas.

It would be nice if loading another autosave from the current replay could be done without a full reload, though this may be hard to do.

It should also be investigated how much speed-up can be achieved if the replay is run in the background (without screen updates) for seeking directly to a given time point. I suppose this part is the easiest, and it's useful alone as well for fast forwarding.

**Implementation steps**
- [ ] add fast forward to user specified time functionality to replay watching
- [ ] find efficient way to compress deltas between savegames
- [ ] include autosaves in replay files
- [ ] add "rewind" to user specified time functionality to replay watching

**Comment by Noordfrees** [comment]
Why would they have to be added to the replay files? We could simply create temporary autosave files during playing the replay. It will certainly require a full reload though, simply applying a delta could be a nightmare since there are so many objects to manipulate.
I suspect fast-forwarding will not gain us very much of a speed improvement since rendering is already in a separate thread, but a small gain could be possible.

**Comment by tothxa** [comment]
2 reasons for storing snapshots:

1. saving the game always needs several seconds of pauses (that's why I proposed using the already created autosaves)
2. it would allow jumping forward quicker than replaying everything even if the replay hadn't been watched before

**Comment by Noordfrees** [comment]
Ok makes sense. After #5645 it should actually be quite easy to embed additional savegames within the command log.

**Comment by tothxa** [comment]
Speaking of embedding things: When replays are a single file, it should be possible to merge replays when the game crashes or is suspended (or even if it is branched). This needs checking that the starting game state of the second one matches the game state of the first one at the same gametime, and truncating the first one at that point if necessary in the merged replay.

May I add this to the checklist, or should I move it to a separate feature request?

**Comment by tothxa** [comment]
As for deltas: I made an experiment with autosaves from my tournament match with kaputtnik using xdelta, but it's not too promising. I was only able to get less than 50% size reduction – not much better when comparing contents file-by-file than when just comparing the compressed `.wgf` files, even though many parts are almost identical and thus compress really well. I'm sure it must be possible to come up with better, but it'll have to be "domain specific" unfortunately…

I'll try with some different games before drawing the final conclusion though.
