### ISSUE TITLE
More automation and sanity checking for map tags by the editor

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5657]
Some more of the map tag setting in the editor should be automated or at least sanity-checked.

(after #5653 is merged)

**Implementation steps**
- [ ] auto-select teams tags for configured teams
- [ ] don't allow teams tags for which there are not enough player slots
- [ ] remind user to set teams for all checked teams tag which haven't got matching team suggestions
- [ ] suggest theme based on most common terrain climate (only over some threshold, e.g. 75%, but may need to use different weight for useful land than water and unwalkable terrains, and relevant immovables should also be considered)
- [ ] bonus: check balance
- [ ] opinions: suggest setting ferry range when disabled?
