### ISSUE TITLE
Improve box layout logic

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#6036]
**Is your feature request related to a problem? Please describe.**
The UI layout using boxes is convenient but has some quirks that can cause unexpected layout issues (mostly during resizing).

**Describe the solution you'd like**
The box layout logic should be cleaned up to provide a more robust and intuitive layout behavior. 

**Additional context**
Re #5631, #6016 and associated regressions

**Implementation steps**
- [ ] Add item type ItemBox to handle nested boxes
  - [ ] Propagate `set_max_size` calls to child boxes to stay in bounds 
    (currently the bottom most child box has to set the correct size, otherwise it overflows)
  - [ ] Do not assign variable size larger than childs max size 
    (this is what max size should limit, right?)
- [ ] Do not always update desired size on `add` or `set_max_size` to prevent resizing issues 
   (the parents desired layout is implicitly overridden and might break)
- [ ] Sanitize box content size to fit into defined dimensions
  - [ ]  Reduce recursive calls of `set_desired_size` → `update_desired_size` → `layout`
  - [ ] Fix overflowing layouts, the sum of all item sizes in a box should never exceed the actual box size
