### ISSUE TITLE
The settings of a random map should be available in the map itself

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#6199]
See: https://www.widelands.org/forum/topic/5865/

**Implementation steps**
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by knarrff** [comment]
As suggestion:

# Implementation steps:

- [ ] figure out and document what the necessary data is (random seed and/or id and possibly more?)
- [ ] create variables within "game/map scope" to hold the necessary data
- [ ] set those variables during map creation
- [ ] save/load those variables as part of a map save/load
- [ ] provide display of those variable in-game
