### ISSUE TITLE
make trainigsites healing soldiers as well

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#6504]
see (https://www.widelands.org/forum/topic/6043/)

**Describe the solution you'd like**
soldiers shall be healed not only in militarysites and Warehouses but in trainingsites as well

**Implementation steps**
- [ ] add c++ code of militarysites to trainingsites
- [ ] add heal per second definition to all trainingsites. Values to be discussed
- [ ] add compatibility code

**Comment by bunnybot** [comment]
Mirrored on Codeberg as [#CB4865](https://codeberg.org/wl/widelands/issues/4865).

**Comment by cake-pie** [comment]
-1 strong disagree, this doesn't work from flavor perspective.

Soldiers inside military buildings and warehouses are "resting" and not fighting, so they can recover from injury.

Soldiers in training sites aren't fighting, however they are undergoing training. They might be sparring to improve attack, or running obstacle courses to improve evade, or doing some physical exercise to bulk up and increase health. They are certainly not there for "rest and recovery".

**Comment by bunnybot** [comment]
[<img align='left' src='https://codeberg.org/avatars/94062fb4c3e503b6434a88938aca6486630fcdfe4d13f557dc2ef771ba3943d8' alt='frankystone' height='48' />](https://codeberg.org/frankystone)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/4865#issuecomment-2185557)*
*On Tue Aug 20 08:16:35 CEST 2024, [**frankystone**](https://codeberg.org/frankystone) wrote:*

---

I am not against this. As long healing in trainingsites will be applied before any training step is made.

> Soldiers inside military buildings and warehouses are "resting" and not fighting, so they can recover from injury.

Soldiers in trainingsites do have also some time for "resting". Training isn't done in one go, especially if more than one soldier is in the trainingsite.

Strong players will not need this anyway, because they usually only use fully trained soldiers for fighting. For beginners healing in trainingsites  might be helpful.

**Comment by bunnybot** [comment]
[<img align='left' src='https://codeberg.org/avatars/593dc43e2444c25db9481960e5b693ab' alt='tothxa' height='48' />](https://codeberg.org/tothxa)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/4865#issuecomment-2185648)*
*On Tue Aug 20 09:23:35 CEST 2024, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:*

---

I think @cake-pie has a point. But that means that the logical and real-world analogous fix would be to never send injured soldiers to training sites at all.

**Comment by hessenfarmer** [comment]
from my perspective it is normally highly improbable that an injured soldier get sent to a trainingsite. (only if he is the last one in a warehouse, while all garrisons at military buildings have been filled and an empty slot in a ts is available, which is pretty much never the case while fights are going on) 
so as it is not a real improvement for the game mechanics I'll close this PR.

**Comment by hessenfarmer** [comment]
from my perspective it is normally highly improbable that an injured soldier get sent to a trainingsite. (only if he is the last one in a warehouse, while all garrisons at military buildings have been filled and an empty slot in a ts is available, which is pretty much never the case while fights are going on) 
so as it is not a real improvement for the game mechanics I'll close this PR.

**Comment by hessenfarmer** [comment]
from my perspective it is normally highly improbable that an injured soldier get sent to a trainingsite. (only if he is the last one in a warehouse, while all garrisons at military buildings have been filled and an empty slot in a ts is available, which is pretty much never the case while fights are going on)
so as it is not a real improvement for the game mechanics I'll close this PR.
